from src.common.enum import EnumData


class UserRolesEnum(EnumData):

    ROLE_VSM_DOCFLOW_BASIC = "ROLE_VSM_DOCFLOW_BASIC"
    ROLE_VSM_DOCFLOW_REGISTRATOR = "ROLE_VSM_DOCFLOW_REGISTRATOR"
    ROLE_VSM_DOCFLOW_ADMIN = "ROLE_VSM_DOCFLOW_ADMIN"
