"""Document Files

Revision ID: 0cd143da3594
Revises: e021e288880a
Create Date: 2025-09-25 16:49:29.839237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd143da3594'
down_revision: Union[str, Sequence[str], None] = 'e021e288880a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_document_files',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents_document.id'], name=op.f('fk_document_document_files_document_id_documents_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_document_files')),
    sa.UniqueConstraint('file_id', name=op.f('uq_document_document_files_file_id'))
    )
    op.create_index(op.f('ix_document_document_files_document_id'), 'document_document_files', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_document_files_document_id'), table_name='document_document_files')
    op.drop_table('document_document_files')
    # ### end Alembic commands ###
