"""correspondence DocumentAddress

Revision ID: 0ef80fa818aa
Revises: 8c195b320101
Create Date: 2025-09-29 17:34:03.949999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ef80fa818aa'
down_revision: Union[str, Sequence[str], None] = '8c195b320101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correspondence_document_address',
    sa.Column('party_type', sa.Enum('SENDER', 'RECIPIENT', name='document_party_type_enum'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('external_user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('is_responsible', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['correspondence_document.id'], name=op.f('fk_correspondence_document_address_document_id_correspondence_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correspondence_document_address'))
    )
    op.create_index(op.f('ix_correspondence_document_address_document_id'), 'correspondence_document_address', ['document_id'], unique=False)
    op.create_index(op.f('ix_correspondence_document_address_external_user_id'), 'correspondence_document_address', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_correspondence_document_address_organization_id'), 'correspondence_document_address', ['organization_id'], unique=False)
    op.create_index(op.f('ix_correspondence_document_address_party_type'), 'correspondence_document_address', ['party_type'], unique=False)
    op.create_index(op.f('ix_correspondence_document_address_user_id'), 'correspondence_document_address', ['user_id'], unique=False)
    op.create_table('correspondence_document_registration',
    sa.Column('registration_number_id', sa.UUID(), nullable=True),
    sa.Column('external_registration_number', sa.String(length=30), nullable=True),
    sa.Column('external_registration_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['correspondence_document.id'], name=op.f('fk_correspondence_document_registration_document_id_correspondence_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_number_id'], ['registration_registration_number.id'], name=op.f('fk_correspondence_document_registration_registration_number_id_registration_registration_number'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correspondence_document_registration'))
    )
    op.create_index(op.f('ix_correspondence_document_registration_document_id'), 'correspondence_document_registration', ['document_id'], unique=False)
    op.create_index(op.f('ix_correspondence_document_registration_registration_number_id'), 'correspondence_document_registration', ['registration_number_id'], unique=True)
    op.drop_index(op.f('ix_correspondense_document_registration_document_id'), table_name='correspondense_document_registration')
    op.drop_index(op.f('ix_correspondense_document_registration_registration_number_id'), table_name='correspondense_document_registration')
    op.drop_table('correspondense_document_registration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correspondense_document_registration',
    sa.Column('registration_number_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('external_registration_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('external_registration_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['correspondence_document.id'], name=op.f('fk_correspondense_document_registration_document_id_cor_7a3f'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_number_id'], ['registration_registration_number.id'], name=op.f('fk_correspondense_document_registration_registration_nu_391e'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correspondense_document_registration'))
    )
    op.create_index(op.f('ix_correspondense_document_registration_registration_number_id'), 'correspondense_document_registration', ['registration_number_id'], unique=True)
    op.create_index(op.f('ix_correspondense_document_registration_document_id'), 'correspondense_document_registration', ['document_id'], unique=False)
    op.drop_index(op.f('ix_correspondence_document_registration_registration_number_id'), table_name='correspondence_document_registration')
    op.drop_index(op.f('ix_correspondence_document_registration_document_id'), table_name='correspondence_document_registration')
    op.drop_table('correspondence_document_registration')
    op.drop_index(op.f('ix_correspondence_document_address_user_id'), table_name='correspondence_document_address')
    op.drop_index(op.f('ix_correspondence_document_address_party_type'), table_name='correspondence_document_address')
    op.drop_index(op.f('ix_correspondence_document_address_organization_id'), table_name='correspondence_document_address')
    op.drop_index(op.f('ix_correspondence_document_address_external_user_id'), table_name='correspondence_document_address')
    op.drop_index(op.f('ix_correspondence_document_address_document_id'), table_name='correspondence_document_address')
    op.drop_table('correspondence_document_address')
    # ### end Alembic commands ###
