"""correspondence DocumentConfidential enum

Revision ID: 7b4cbe6769dc
Revises: 
Create Date: 2025-09-29 14:58:02.424086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4cbe6769dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correspondence_document',
    sa.Column('document_type', sa.Enum('INCOMING', 'OUTGOING', 'ASSIGNMENT', 'ASSIGNMENT_INTERNAL', 'PROTOCOL', 'ORDER', 'DIRECTIVE', 'NOTES', name='correspondence_document_document_type_enum'), nullable=False),
    sa.Column('system_number', sa.String(length=25), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('paper_count', sa.Integer(), nullable=True),
    sa.Column('attachment_description', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correspondence_document'))
    )
    op.create_table('correspondence_document_confidential',
    sa.Column('confidential', sa.Enum('DOCUMENT_PRIVACY_LEVEL_OFFICIAL_USE_ONLY', 'DOCUMENT_PRIVACY_LEVEL_CONFIDENTIAL', 'DOCUMENT_PRIVACY_LEVEL_COMMERCIAL_SECRET', 'DOCUMENT_PRIVACY_LEVEL_PERSONAL_DATA', name='document_confidential_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['correspondence_document.id'], name=op.f('fk_correspondence_document_confidential_document_id_correspondence_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correspondence_document_confidential')),
    sa.UniqueConstraint('document_id', 'confidential', name='uq_doc_confidential')
    )
    op.create_index(op.f('ix_correspondence_document_confidential_document_id'), 'correspondence_document_confidential', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correspondence_document_confidential_document_id'), table_name='correspondence_document_confidential')
    op.drop_table('correspondence_document_confidential')
    op.drop_table('correspondence_document')
    # ### end Alembic commands ###
