"""Document creator_id

Revision ID: f2dcd0391212
Revises: 0cd143da3594
Create Date: 2025-09-26 10:26:44.603040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2dcd0391212'
down_revision: Union[str, Sequence[str], None] = '0cd143da3594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_document', sa.Column('creator_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents_document', 'creator_id')
    # ### end Alembic commands ###
