"""Document sytem numbers

Revision ID: f95689c3128f
Revises: 6d84b0ec9f4a
Create Date: 2025-09-26 14:53:45.776614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95689c3128f'
down_revision: Union[str, Sequence[str], None] = '6d84b0ec9f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_document', sa.Column('system_number', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents_document', 'system_number')
    # ### end Alembic commands ###
