from enum import StrEnum


class DocumentConfidentialTypeEnum(StrEnum):
    DOCUMENT_PRIVACY_LEVEL_OFFICIAL_USE_ONLY = (
        "ROLE_VSM_DOCFLOW_PRIVACY_LEVEL_OFFICIAL_USE_ONLY"
    )
    DOCUMENT_PRIVACY_LEVEL_CONFIDENTIAL = "ROLE_VSM_DOCFLOW_PRIVACY_LEVEL_CONFIDENTIAL"
    DOCUMENT_PRIVACY_LEVEL_COMMERCIAL_SECRET = (
        "ROLE_VSM_DOCFLOW_PRIVACY_LEVEL_COMMERCIAL_SECRET"
    )
    DOCUMENT_PRIVACY_LEVEL_PERSONAL_DATA = (
        "ROLE_VSM_DOCFLOW_PRIVACY_LEVEL_PERSONAL_DATA"
    )
